<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 11px; color: #1a1a1a; margin: 0; padding: 30px; }
        .company-name { font-size: 20px; font-weight: bold; color: #E31E24; }
        .doc-title { font-size: 22px; font-weight: bold; text-align: right; }
        .ref { text-align: right; color: #666; font-size: 12px; }
        .label { font-size: 9px; text-transform: uppercase; color: #999; letter-spacing: 1px; margin-bottom: 3px; }
        .value { font-size: 12px; font-weight: bold; margin-bottom: 14px; }
        .detail { font-size: 10.5px; color: #333; line-height: 1.5; }
        .amount-box { border: 2px solid #1a1a1a; padding: 14px 16px; margin: 18px 0; }
        .amount-box .big { font-size: 22px; font-weight: bold; }
        table.sum { width: 300px; margin-left: auto; }
        table.sum td { padding: 4px 0; font-size: 11px; }
        table.sum td.num { text-align: right; }
        .footer { margin-top: 40px; text-align: center; font-size: 9px; color: #999; }
    </style>
</head>
<body>
    <table style="width: 100%; border: none;">
        <tr>
            <td style="border: none;">@include('pdfs._brand', ['h' => 40])<div class="company-name">{{ $company['name'] }}</div>
                <div class="detail">KRA PIN: {{ $company['kra_pin'] }}<br>{{ $company['po_box'] }}<br>{{ $company['phone'] }} &middot; {{ $company['email'] }}</div>
            </td>
            <td style="border: none;">
                <div class="doc-title">RECEIPT</div>
                <div class="ref">No. {{ $payment->reference }}</div>
                <div class="ref">Received {{ $payment->paid_at->format('d M Y') }}</div>
            </td>
        </tr>
    </table>

    <table style="width: 100%; margin-top: 22px">
        <tr>
            <td style="width: 50%; vertical-align: top">
                <div class="label">Received from</div>
                <div class="value">{{ $payment->customer?->name }}</div>
                @if ($payment->customer?->kra_pin)<div class="detail">KRA PIN: {{ $payment->customer->kra_pin }}</div>@endif
            </td>
            <td style="width: 50%; vertical-align: top">
                <div class="label">Against invoice</div>
                <div class="value">{{ $invoice?->reference ?? '-' }}</div>
                <div class="label">Payment method</div>
                <div class="value">{{ $payment->method }}</div>
            </td>
        </tr>
    </table>

    <div class="amount-box">
        <div class="label">Amount received</div>
        <div class="big">{{ $payment->currency_code }} {{ number_format($payment->amount_minor / 100, 2) }}</div>
    </div>

    @if ($invoice)
        <table class="sum">
            <tr><td>Invoice total</td><td class="num">{{ $invoice->currency_code }} {{ number_format($invoice->amount_minor / 100, 2) }}</td></tr>
            <tr><td>Paid to date</td><td class="num">{{ $invoice->currency_code }} {{ number_format($invoice->paid_minor / 100, 2) }}</td></tr>
            <tr><td><b>Balance on the invoice</b></td><td class="num"><b>{{ $invoice->currency_code }} {{ number_format($invoice->balanceMinor() / 100, 2) }}</b></td></tr>
        </table>
    @endif

    <div class="detail" style="margin-top: 26px">Recorded by {{ $payment->recordedBy?->name ?? '-' }}. Thank you for your payment.</div>
    <div class="footer">This receipt was generated by the AEA Service Management System.</div>
</body>
</html>
